CREATE DATABASE IF NOT EXISTS expense_db;
USE expense_db;

CREATE TABLE users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(50) NOT NULL UNIQUE,
  password VARCHAR(100) NOT NULL
);

CREATE TABLE expenses (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user VARCHAR(50) NOT NULL,
  category VARCHAR(50),
  amount DOUBLE,
  date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
